# Starter pipeline
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1)(39871908-78ed-4ef9-adbf-cb5c701334e3)'
    subscriptionId: '39871908-78ed-4ef9-adbf-cb5c701334e3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG3'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/de8899/pline/master/template.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/de8899/pline/master/parameters.json'
    deploymentMode: 'Incremental'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      chmod ug+x testbash.sh
      sudo chmod ugo+x testbash.sh

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'bash testbash.sh'
    